services:
  # Laravel Backend
  laravel:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./ecommerce-stock-management:/var/www/html
    environment:
      - DB_CONNECTION=mongodb
      - DB_DATABASE=ecommerce_stock
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - redis
    networks:
      - app-network

  # React Frontend (optional for now, since we're focusing on backend)
  # react:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000/api
  #   depends_on:
  #     - laravel
  #   networks:
  #     - app-network

  # MongoDB
  # mongodb:
  #   image: mongo:7.0
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: ecommerce_stock
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - app-network

  # Redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
